export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_NEW_CONVERSATION = "ADD_NEW_CONVERSATION";
export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_USER_MESSAGES = "SET_USER_MESSAGES";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";
